### ISSUE TITLE
Sort scripts by official and unofficial

### ISSUE THREAD

**Issue by llamositopia** [KitbogaCodeville/kitboga-codeville#9]
I propose that scripts written or used by Kitboga be placed in a separate root folder, to differentiate community-submitted scripts from stream-created scripts. Open for discussion.

**Comment by yukihyou** [comment]
Updooted, definitely support.

Was considering asking about how to sort as well - by language/tech used? By "type" (annoying, functional, etc) or by something else?

**Comment by llamositopia** [comment]
I think language would be the easiest one for people to easily classify. It raises a little bit of grey area for projects that use multiple languages, but those are rare and usually have a core language that dominates the project.

**Comment by yukihyou** [comment]
So like this?
```
\Community
- \AHK
  - \notepad-ahk
- \CSharp
  - \NewTreeCS
\Official
- \AHK
  - \notepad-bossfight
```

**Comment by llamositopia** [comment]
Absolutely! I'll leave this open for another few days for more discussion before acting on it.

**Comment by llamositopia** [comment]
With the massive influx of people submitting PRs to the repository, I feel this is even more important now. I have opened a PR #17
